version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=first_api_go_lang
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data